### ISSUE TITLE
Memory Storage Doesn't Support Specifying Queues Directly for a Specific Job

### ISSUE THREAD

**Issue by wrakocy** [HangfireIO/Hangfire.InMemory#15]
Hi all,

I had posted this on the Hangfire board, but thinking that this is the better forum, so deleted it there and migrating here.

My issue: after upgrading from Hangfire.InMemory 1.7.x to 1.8.14, I can no longer schedule recurring jobs to run on specific queues (without using the QueueAttribute, which won't work for us because we run the same jobs in parallel on different queues).

We set up in memory storage like so:

`services.AddHangfire(options => options.UseMemoryStorage());`

...but are hitting up against the following error during startup:

_System.NotSupportedException: 'Current storage doesn't support specifying queues directly for a specific job. Please use the QueueAttribute instead.'_

Here is how I am scheduling the recurring job in version 1.8.14:

       ` RecurringJob.AddOrUpdate<MyJob>(
              "My Job", 
             "QueueName", 
              x => x.RunAsync(), "45 11,13,17,20 * * 1-5",  
              new RecurringJobOptions { TimeZone = EasternTime.Zone });`

In 1.7.x we were specifying queue name on RecurringJobOptions like so:

       `RecurringJob.AddOrUpdate<MyJob>(
             "My Job", 
              x => x.RunAsync(), 
              "45 11,13,17,20 * * 1-5",  
              new RecurringJobOptions { TimeZone = EasternTime.Zone, QueueName = "QueueName" });`

...but that approach now generates compiler warnings in 1.8, due to deprecation of QueueName on RecurringJobOptions.

Can anyone recommend a workaround for this short of reverting to 1.7.x or ignoring/disabling the compiler warnings?

Cheers!

**Comment by odinserj** [comment]
Hi, please ensure you are using `Hangfire.InMemory` package (official one), and not the `Hangfire.MemoryStorage` (community-based). Please see the https://github.com/HangfireIO/Hangfire.InMemory readme for details.

**Comment by wrakocy** [comment]
Hi @odinserj. Thanks very much for the response and sorry for the delayed follow up. 

You're spot on. We were in fact referencing Hangfire.MemoryStorage . After swapping it out for the official InMemory package and tweaking our setup, everything is behaving as expected. Thanks so much for the assist!

**Comment by odinserj** [comment]
No worries for the delay, my responses suffer from them too unfortunately.

Thanks for confirming it works now!
