### ISSUE TITLE
NotNull check on GetFirstByLowestScoreFromSet

### ISSUE THREAD

**Issue by AnatoleF** [HangfireIO/Hangfire.InMemory#3]
This is a minor issue and mainly only noticeable when debugging in vscode. But it is annoying when breakpoints are enabled for all exceptions when debugging.

When using InMemory, the following exception is thrown once the hosted service has started:

> Exception thrown: 'System.ArgumentNullException' in Hangfire.InMemory.dll

The exception is taking place when [InMemoryConnection.GetFirstByLowestScoreFromSet](https://github.com/HangfireIO/Hangfire.InMemory/blob/fbf8d08367cd7b34ba5192ffba7dadcf1b82057d/src/Hangfire.InMemory/InMemoryConnection.cs#L350) is being called because of the [NotNull] on the key. I noticed that in the main library, [SqlServerConnection.GetFirstByLowestScoreFromSet](https://github.com/HangfireIO/Hangfire/blob/16b25e658be3bbcb7d03f24a8544703aecb697c8/src/Hangfire.SqlServer/SqlServerConnection.cs#L359) does not have [NotNull].

Can this check be removed to match SqlServerConnection.GetFirstByLowestScoreFromSet?
Since when you call [RecurringJobScheduler.IsBatchingAvailable](https://github.com/HangfireIO/Hangfire/blob/16b25e658be3bbcb7d03f24a8544703aecb697c8/src/Hangfire.Core/Server/RecurringJobScheduler.cs#L406) you pass a null.

**Comment by odinserj** [comment]
This exception is used as a trick to understand whether this method implemented or not. However it will be possible with Hangfire 1.8 to use another feature for this. So once it's released I will resolve this problem. Thanks for reporting this.
