### ISSUE TITLE
Confusion between UseMemoryStorage and UseInMemoryStorage

### ISSUE THREAD

**Issue by seangwright** [HangfireIO/Hangfire.InMemory#7]
In the [README](https://github.com/HangfireIO/Hangfire.InMemory/blob/24df82f1fb9e0965617f383b6ffb38e9238e82ca/README.md#installation), the instructions say to "use the new `UseMemoryStorage` method", but the code example that follows uses `UseInMemoryStorage`.

Then, the latest code in [GlobalConfigurationExtensions.cs](https://github.com/HangfireIO/Hangfire.InMemory/blob/52feddadf9dd5ab7f3524c319df3535a4be40976/src/Hangfire.InMemory/GlobalConfigurationExtensions.cs#L9) defines a method `UseInMemoryStorage`, but when I get the latest NuGet package (v1.7.0.0), the method is named `UseMemoryStorage`.

So it seems like the docs are contradictory _and_ the NuGet package doesn't match up with what is in GitHub.

I'd be happy to make a PR to update the docs, but I'm confused about which method name is the "correct" one.

**Comment by odinserj** [comment]
There are two packages, official `Hangfire.InMemory` and community-based `Hangfire.MemoryStorage`. The former one's latest version is 0.3.5, so looks like you are simply using another package, that's why the differences.

**Comment by marchy** [comment]
Thanks, got caught by this too!
Gotta get those download counts up so that the official one ranks higher up the list! 😄

**Comment by codehunter13** [comment]
The documentation uses both:
![image](https://github.com/HangfireIO/Hangfire.InMemory/assets/7559059/59445223-70bf-4814-9f27-b8c321d30613)

**Comment by odinserj** [comment]
Finally found the confusing wording and fixed it! 😄
