### ISSUE TITLE
Memory Cleanup Issue

### ISSUE THREAD

**Issue by TyrannusX** [HangfireIO/Hangfire.InMemory#8]
Hello. I have a long running process, and according to memory analysis the _locks dictionary inside the InMemoryState class is not cleaning up properly. Besides the JobExpirationTimeout provided by Hangfire, is there anything else that can be done with releasing memory?

**Comment by TyrannusX** [comment]
To add onto my original post, I did a quick test and noticed that successful jobs were being removed from the InMemoryState _jobs dictionary once the JobExpirationTimeout was hit, but are never cleared from the _locks dictionary. That seems like a bug to me, and successful jobs should also be cleared from _locks too.

**Comment by odinserj** [comment]
Thanks a lot for your investigation and report! I've fixed the issue and released version 0.3.6, so please feel free to upgrade.
